@host=http://localhost:5000
### END VARS

### Get GRPC
GET /

### GET Kafka
GET /kafka

### Post Message
POST / 
Content-Type: application/json

{
    "message": "{{$input message}}"
}

### Post invalid json

POST / 
Content-Type: application/json

{
    "message"
}

### Create new topic
POST /new_topic
Content-Type: application/json
{
  "topic": "topikki"
}


### Send to kafka grpc response
POST /send_producer
Content-Type: application/json
{
  "topic": "topikki",
  "number1": 1,
  "number2": 2
}

### Start consumer with topic name
POST /start_consumer
Content-Type: application/json
{
  "topic": "topikki"
}
### Distriputed ML Basic
POST /suggest_enhancements 
Content-Type: application/json

{
    "input": "Ping answer with Pong"
}
### Distriputed ML
POST /suggest_enhancements 
Content-Type: application/json

{
    "input": "{{$input message}}"
}