FROM debian:bookworm-slim
RUN apt-get update && apt-get upgrade -y
RUN apt-get install python3-dev python3-pip -y 
WORKDIR app
COPY . .
RUN pip install -r requirements.txt --break-system-packages
EXPOSE 8084
ENTRYPOINT ["waitress-serve", "--listen=*:8084", "app:app"]