from debian:bookworm-slim
run apt-get update && apt-get upgrade -y
run apt-get install python3-dev python3-pip -y 
workdir app
copy . .
run pip install -r requirements.txt --break-system-packages
#run python3 -m grpc_tools.protoc -I=. --python_out=. --pyi_out=. --grpc_python_out=. *.proto
expose 50052
cmd ["python3", "server.py"]