apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-broker-0
  namespace: microservices
data:
  broker-id: "1"
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../cc.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: broker
  name: broker
  namespace: microservices
spec:
  clusterIP: "None"
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
    - name: "29092"
      port: 29092
      targetPort: 29092
    - name: "29093"
      port: 29093
      targetPort: 29093
  selector:
    io.kompose.service: broker
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../cc.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: broker
  name: broker
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: broker
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../cc.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: broker
    spec:
      containers:
        - env:
            # - name: broker-1
            #   value: "1"
            # - name: POD_NAME
            #   valueFrom:
            #     fieldRef:
            #       fieldPath: metadata.name
            # - name: TEST
            #   valueFrom:
            #     configMapKeyRef:
            #       name: kafka-broker-$(POD_INDEX)  # Reference the correct ConfigMap
            #       key: broker-id
            - name: CLUSTER_ID
              value: MkU3OEVBNTcwNTJENDM2Qk
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: 1@broker:29093
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
            - name: KAFKA_LOG_DIRS
              value: /tmp/kraft-combined-logs
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_PROCESS_ROLES
              value: broker,controller
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
          # command: ["/bin/sh", "-c", "export numeric_value=$(echo $POD_NAME | sed 's/[^0-9]*//g'); exec /usr/bin/kafka-server-start"]
          image: docker.io/apache/kafka:latest
          name: broker
          ports:
            - containerPort: 9092
              protocol: TCP
            - containerPort: 29092
              protocol: TCP
            - containerPort: 29093
              protocol: TCP
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "2"
      restartPolicy: Always
---