apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../cc.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: calculator
  name: calculator
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: calculator
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../cc.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: calculator
    spec:

      # nodeSelector:
      #   role-microservices: "true"
      priorityClassName: "medium-priority"  # Set priority to medium for calculator service
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #             - key: "role-microservices"
      #               operator: In
      #               values:
      #                 - "true"  # Ensure calculator runs on nodes with standard memory
        # podAntiAffinity:
        #   preferredDuringSchedulingIgnoredDuringExecution:
        #     - weight: 100
        #       podAffinityTerm:
        #         labelSelector:
        #           matchExpressions:
        #             - key: io.kompose.service
        #               operator: In
        #               values:
        #                 - calculator
        #         topologyKey: "kubernetes.io/hostname" 
      containers:
        - env:
            - name: GRPC_DNS_RESOLVER
              value: native
            - name: MONGO_URI
              value: mongodb://<REPLACE>:<REPLACE>@mongo:27017
          image: distributed-systems-2025-calculator
          name: calculator
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50052
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      restartPolicy: Always
