apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../cc.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: control
  namespace: microservices
  name: control
spec:
  type: LoadBalancer
  ports:
    - name: "5000"
      port: 5000
      targetPort: 8080
  selector:
    io.kompose.service: control
