apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-scaledobject
  namespace: microservices
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment  
    name: kafkaservice    # Deployment to scale
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: kafka
    metadata:
      # brokerList: "broker.microservices.svc.cluster.local:9092"
      bootstrapServers: "broker.microservices.svc.cluster.local:29092"
      consumerGroup: "my-group"
      topic: "topikki"
      lagThreshold: "10"              # Scale up if lag exceeds 10 messages
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 60  # Wait 60 seconds before scaling up
          policies:
            - type: Percent
              value: 50
              periodSeconds: 15
        scaleDown:
          stabilizationWindowSeconds: 60  # Wait 60 seconds before scaling down
          policies:
            - type: Percent
              value: 30
              periodSeconds: 30