apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../cc.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: kafkaservice
  name: kafkaservice
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafkaservice
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../cc.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: kafkaservice
    spec:
      # priorityClassName: "medium-priority"  # Set priority to medium for calculator service
      containers:
        - env:
            - name: KAFKA_URI
              value: broker:29092
          image: distributed-systems-2025-kafkaservice
          imagePullPolicy: Never
          name: kafkaservice
          ports:
            - containerPort: 8084
              protocol: TCP
          # resources:
          #   requests:
          #     memory: "1Gi"
          #     cpu: "500m"
          #   limits:
          #     memory: "2Gi"
          #     cpu: "1000m"
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "2"
      restartPolicy: Always
