FROM python:3.10-slim
# run apk upgrade
# run apk add python3 py3-pip
WORKDIR /app

# COPY requirements.txt .
# RUN pip install --no-cache-dir -r requirements.txt
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

EXPOSE 50052
# ENTRYPOINT ["waitress-serve", "server:server"]
CMD ["python", "server.py"]